// Enum & constant gốc — đồng bộ với docs/Database_Schema.md và Backend_Features_and_API_Spec.md.

const ROLE = Object.freeze({ OWNER: 'OWNER', ADMIN: 'ADMIN', MEMBER: 'MEMBER' });
const ROLE_VALUES = Object.values(ROLE);
const ROLE_RANK = Object.freeze({ MEMBER: 1, ADMIN: 2, OWNER: 3 });

const MEMBER_STATUS = Object.freeze({ ACTIVE: 'ACTIVE', REMOVED: 'REMOVED' });
const MEMBER_STATUS_VALUES = Object.values(MEMBER_STATUS);

const INVITATION_ROLE_VALUES = ['ADMIN', 'MEMBER'];
const INVITATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
});
const INVITATION_STATUS_VALUES = Object.values(INVITATION_STATUS);

const TASK_STATUS = Object.freeze({
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  IN_REVIEW: 'IN_REVIEW',
  DONE: 'DONE',
});
const TASK_STATUS_VALUES = Object.values(TASK_STATUS);

const DEFAULT_PROJECT_STATUSES = [
  { key: 'TODO', label: 'To Do', order: 0 },
  { key: 'IN_PROGRESS', label: 'In Progress', order: 1 },
  { key: 'IN_REVIEW', label: 'In Review', order: 2 },
  { key: 'DONE', label: 'Done', order: 3 },
];

const PRIORITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
});
const PRIORITY_VALUES = Object.values(PRIORITY);

const ENTITY_TYPE_VALUES = ['TASK', 'PROJECT', 'WORKSPACE', 'COMMENT', 'INVITATION'];

const NOTIFICATION_TYPE_VALUES = [
  'TASK_ASSIGNED',
  'TASK_STATUS_CHANGED',
  'TASK_DUE_SOON',
  'TASK_OVERDUE',
  'COMMENT_ADDED',
  'COMMENT_REPLY',
  'MENTIONED',
  'MEMBER_INVITED',
  'MEMBER_JOINED',
  'ROLE_CHANGED',
  'REMOVED_FROM_WORKSPACE',
  'PROJECT_CREATED',
];

const ACTIVITY_TYPE_VALUES = [
  'WORKSPACE_CREATED',
  'PROJECT_CREATED',
  'MEMBER_INVITED',
  'MEMBER_JOINED',
  'TASK_CREATED',
  'TASK_STATUS_CHANGED',
  'TASK_ASSIGNED',
  'TASK_UNASSIGNED',
  'TASK_PRIORITY_CHANGED',
  'TASK_DUE_CHANGED',
  'TASK_RENAMED',
  'COMMENT_ADDED',
  'TASK_ATTACHMENT_ADDED',
  'TASK_DELETED',
];

const LIMITS = Object.freeze({
  PAGE_DEFAULT: 1,
  LIMIT_DEFAULT: 20,
  LIMIT_MAX: 100,

  TASK_LABELS_MAX: 10,
  CHECKLIST_MAX: 50,
  ATTACHMENTS_MAX: 20,

  INVITATION_TTL_DAYS: 7,
  WORKSPACE_OWNED_MAX: 10,

  POSITION_GAP: 1024,
  POSITION_MIN_GAP: 0.0001,
});

module.exports = {
  ROLE,
  ROLE_VALUES,
  ROLE_RANK,
  MEMBER_STATUS,
  MEMBER_STATUS_VALUES,
  INVITATION_ROLE_VALUES,
  INVITATION_STATUS,
  INVITATION_STATUS_VALUES,
  TASK_STATUS,
  TASK_STATUS_VALUES,
  DEFAULT_PROJECT_STATUSES,
  PRIORITY,
  PRIORITY_VALUES,
  ENTITY_TYPE_VALUES,
  NOTIFICATION_TYPE_VALUES,
  ACTIVITY_TYPE_VALUES,
  LIMITS,
};
